version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "GHA CI"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    labels:
      - "CI"
    schedule:
      interval: "daily"
      time: "05:00" # UTC: 23:00 CST, 00:00 CDT
